-- External table definition
 
CREATE DIRECTORY OBI_SESSION_DIR AS '/home/oracle/obi-clickdata/';
 
GRANT WRITE,READ ON DIRECTORY OBI_SESSION_DIR TO BIEE_BIPLATFORM;
 
DROP TABLE BIEE_BIPLATFORM.OBI_CLICKDATA_STAGE;
 
CREATE TABLE BIEE_BIPLATFORM.OBI_CLICKDATA_STAGE
  (
     CLICK_TS             TIMESTAMP WITH TIME ZONE,
     COOKIE_ORA_BIPS_NQID VARCHAR2(255),
     SAW_USER             VARCHAR2(255),
     SESSIONID            VARCHAR2(255),
     ECID                 VARCHAR2(255),
     REQUESTTYPE          VARCHAR2(255),
     REQUEST              VARCHAR2(255),
     FOLDER               VARCHAR2(255),
     ITEMNAME             VARCHAR2(255),
     EDITORID             VARCHAR2(255),
     REPORTEDITOR         VARCHAR2(255),
     SUBJECTAREA          VARCHAR2(255),
     SATABLE              VARCHAR2(255),
     ACTION               VARCHAR2(255),
     USERAGENT            VARCHAR2(255),
     MOBILE_IND            VARCHAR2(255)
  )
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY OBI_SESSION_DIR
     ACCESS PARAMETERS
       (RECORDS DELIMITED BY '\n'
           BADFILE OBI_SESSION_DIR:'http_requests.bad'
           DISCARDFILE OBI_SESSION_DIR:'http_requests.discard'
           LOGFILE OBI_SESSION_DIR:'http_requests.log'
           SKIP 0
           FIELDS TERMINATED BY ','
           OPTIONALLY ENCLOSED BY '"' AND '"'
           LRTRIM
           MISSING FIELD VALUES ARE NULL
           (
            CLICK_TS                CHAR(4000) DATE_FORMAT TIMESTAMP WITH TIME ZONE MASK 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"',
            COOKIE_ORA_BIPS_NQID    CHAR(4000),
            SAW_USER                CHAR(4000),
            SESSIONID               CHAR(4000),
            ECID                    CHAR(4000),
            REQUESTTYPE             CHAR(4000),
            REQUEST                 CHAR(4000),
            FOLDER                  CHAR(4000),
            ITEMNAME                CHAR(4000),
            EDITORID                CHAR(4000),
            REPORTEDITOR            CHAR(4000),
            SUBJECTAREA             CHAR(4000),
            SATABLE                 CHAR(4000),
            ACTION                  CHAR(4000),
            USERAGENT               CHAR(4000),
            MOBILE_IND               CHAR(4000)
           )
       )
     LOCATION ('http_requests.csv')
  )
  REJECT LIMIT 10;
 
-- Request type definitions
 
-- CREATE TABLE OBI_CLICKDATA_REQUESTGROUP AS SELECT distinct REQUEST,'[Uncategorised]' as REQUEST_GROUP FROM OBI_CLICKDATA WHERE request is not null;
 
DROP TABLE "BIEE_BIPLATFORM"."OBI_CLICKDATA_REQUESTGROUP" ;
  CREATE TABLE "BIEE_BIPLATFORM"."OBI_CLICKDATA_REQUESTGROUP"
   (    "REQUEST" VARCHAR2(255 BYTE),
    "REQUEST_GROUP" VARCHAR2(255 BYTE)
) ;
CREATE UNIQUE INDEX "BIEE_BIPLATFORM"."OBI_CLICKDATA_REQUESTGROUP_PK" ON "BIEE_BIPLATFORM"."OBI_CLICKDATA_REQUESTGROUP" ("REQUEST") ;
ALTER TABLE "BIEE_BIPLATFORM"."OBI_CLICKDATA_REQUESTGROUP" MODIFY ("REQUEST" NOT NULL ENABLE);
ALTER TABLE "BIEE_BIPLATFORM"."OBI_CLICKDATA_REQUESTGROUP" ADD CONSTRAINT "OBI_CLICKDATA_REQUESTGROUP_PK" PRIMARY KEY ("REQUEST") ENABLE;
 
REM INSERTING into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP
SET DEFINE OFF;
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ActionRegistryGetRegistriesByContentType','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ManagePortals','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('Portal','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('RequestAlerts','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('RetrieveIBotInfo','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('LoadSavedFilter','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ManageSessions','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('Maintain','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetReportColumnsXML','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ResolveActionXML','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('Go','Download/Export');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('CheckAuthStatus','Background process');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('PortalModify','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('getReportXmlFromSearchID','Report Interaction');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetColumnInfoXML','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('catalog','Find report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('canAccessSubjectArea','Background process');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('getUserPopulationAccounts','Background process');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('getBIPPreferencesHtml','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ValueTableAjax','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('PortalGo','Run report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetRequestPromptedFilters','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('getDashboardList','Find report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetEncodedMarkup','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('CacheStaticFiles','Background process');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('Logon','Logon');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('getTimezoneInfo','Background process');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetCRColumnsXML','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ConvertFilterToSQL','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('WriteBack','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('Admin','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('reloadAnalysis','Run report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('PreviewGo','Run report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('CheckActionPrivileges','Background process');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('bipublisherEntry','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('CheckDelivery','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('AnswersGetView','Run report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('loadFunctionInTemplate','Background process');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('SaveDashboard','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('downloadFile','Download/Export');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('RetrieveDeliveryProfiles','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('RemoveObjectState','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('unArchiveCatalog','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ResolveNamedAction','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('Sessions','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('JSONRequestColumnMembers','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('CatalogTreeModel','CatalogTreeModel');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ArchiveCatalog','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('RunIBotNow','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('PortalModify2','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('DownloadJobStatus','Download/Export');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('downloadExcelFile','Download/Export');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ClearAlerts','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('CreateBookmark','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('getDelegateUsers','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ColumnFormulaColumnPickerXML','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('Dashboard','Run report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('loadAnswersSubjectAreas','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('JSONRequestTableColumns','Find data');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('PrivilegeAdmin','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('PortalProperties2','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetImagesSelector','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('DocPart','Run report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('Answers','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('bieehome','Home page');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('Logoff','Logoff');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('BIEEHome','Home page');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('getUserPreferencesHtml','Background process');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('RetrieveDevices','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('suggestView','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('PrivilegedAdmin','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetReportMetadata','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('IssueRawSQL','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ActionRegistryGetVisibleActions','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('doItemPermissionsAction','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('getAccountsWITHOUTEffectiveCatalogPerms','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('loadNewDashboardDialog','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetSelectionsMenus','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('switchViewEditor','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('EditDashboard','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('IBotSummary','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('IBotSave','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetColumnMetadata','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('PrivelegeAdmin','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('setPrivilegeAction','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ViewPreview','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('Subscribe','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('SaveSelections','Report Interaction');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('AnswersGetReportEditor','Run report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetMenuItems','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('ReloadDashboard','Run report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('dashboard','Run report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('GetViewGFPRuntimeData','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('uploadFiles','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('refreshSubjectAreaTree','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('suggestViewEditor','Edit report');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('CheckInstanceStatus','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('SwitchConditionTemplate','[Uncategorised]');
Insert into BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP (REQUEST,REQUEST_GROUP) values ('DownloadGuard','Download/Export');
COMMIT;
 
 
-- Any clicks not categorised?
SELECT DISTINCT REQUEST FROM BIEE_BIPLATFORM.OBI_CLICKDATA_STAGE WHERE REQUEST NOT IN (SELECT REQUEST FROM BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP);
SELECT * FROM BIEE_BIPLATFORM.OBI_CLICKDATA_STAGE WHERE REQUEST NOT IN (SELECT REQUEST FROM BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP);
 
-- Build clickdata (initial)
DROP TABLE BIEE_BIPLATFORM.OBI_CLICKDATA;
 
CREATE TABLE BIEE_BIPLATFORM.OBI_CLICKDATA AS
  SELECT A.SESSIONID            SESSIONID,
         ROW_NUMBER()
           OVER (
             PARTITION BY SESSIONID
             ORDER BY CLICK_TS) AS CLICK_NUMBER,
         A.CLICK_TS             CLICK_TS,
         A.SAW_USER             SAW_USER,
         A.REQUESTTYPE          REQUESTTYPE,
         B.REQUEST_GROUP,
         A.REQUEST              REQUEST,
         A.FOLDER               FOLDER,
         A.ITEMNAME             ITEMNAME,
         A.EDITORID             EDITORID,
         A.REPORTEDITOR         REPORTEDITOR,
         A.SUBJECTAREA          SUBJECTAREA,
         A.SATABLE              SATABLE,
         A.ACTION               ACTION,
         A.USERAGENT               USERAGENT,
         A.MOBILE_IND               MOBILE_IND,
         A.COOKIE_ORA_BIPS_NQID COOKIE_ORA_BIPS_NQID,
         A.ECID                 ECID
  FROM   BIEE_BIPLATFORM.OBI_CLICKDATA_STAGE A
         LEFT OUTER JOIN BIEE_BIPLATFORM.OBI_CLICKDATA_REQUESTGROUP B
                      ON A.REQUEST = B.REQUEST
  WHERE  A.REQUEST IS NOT NULL
  ORDER  BY CLICK_TS DESC;
CREATE UNIQUE INDEX "BIEE_BIPLATFORM"."OBI_CLICKDATA_PK" ON "BIEE_BIPLATFORM"."OBI_CLICKDATA" ("SESSIONID", "CLICK_NUMBER") ;
ALTER TABLE "BIEE_BIPLATFORM"."OBI_CLICKDATA" MODIFY ("CLICK_NUMBER" NOT NULL ENABLE);
ALTER TABLE "BIEE_BIPLATFORM"."OBI_CLICKDATA" MODIFY ("SESSIONID" NOT NULL ENABLE);
ALTER TABLE "BIEE_BIPLATFORM"."OBI_CLICKDATA" ADD CONSTRAINT "OBI_CLICKDATA_PK" PRIMARY KEY ("SESSIONID", "CLICK_NUMBER") ENABLE;

CREATE OR REPLACE VIEW BIEE_BIPLATFORM.VW_OBI_CLICKDATA_SESS_SUMMARY AS
WITH FIRST_LAST_CLICK AS
  (SELECT DISTINCT SESSIONID,
    FIRST_VALUE(CLICK_NUMBER) OVER ( PARTITION BY SESSIONID ORDER BY CLICK_NUMBER)                                                          AS FIRST_REPORTRUN_CLICK_NUMBER,
    LAST_VALUE(CLICK_NUMBER) OVER ( PARTITION BY SESSIONID ORDER BY CLICK_NUMBER RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LAST_REPORTRUN_CLICK_NUMBER
  FROM OBI_CLICKDATA
  WHERE REQUEST_GROUP = 'Run report'
  )
SELECT A.SAW_USER,
  A.SESSIONID,
  A.USERAGENT,
  A.MOBILE_IND,
  MIN(A.CLICK_TS)                   AS FIRST_CLICK_TS,
  MAX(A.CLICK_TS)                   AS LAST_CLICK_TS,
  MAX(A.CLICK_TS) - MIN(A.CLICK_TS) AS SESSION_LENGTH,
  COUNT(          *)                AS CLICK_COUNT,
  B.FIRST_REPORTRUN_CLICK_NUMBER    AS FIRST_REPORTRUN_CLICK_NUMBER,
  C.CLICK_TS                        AS FIRST_REPORTRUN_TS,
  C.CLICK_TS - MIN(A.CLICK_TS)      AS TIME_TO_FIRST_REPORTRUN,
  B.LAST_REPORTRUN_CLICK_NUMBER     AS LAST_REPORTRUN_CLICK_NUMBER,
  D.CLICK_TS                        AS LAST_REPORTRUN_TS ,
  E.RUNREPORT_CLICKS,
  E.DL_EXPORT_CLICKS,
  E.FINDREPORT_CLICKS,
  E.FINDDATA_CLICKS,
  E.EDITREPORT_CLICKS
FROM OBI_CLICKDATA A
LEFT OUTER JOIN FIRST_LAST_CLICK B
ON A.SESSIONID = B.SESSIONID
LEFT OUTER JOIN OBI_CLICKDATA C
ON A.SESSIONID                     = C.SESSIONID
AND B.FIRST_REPORTRUN_CLICK_NUMBER = C.CLICK_NUMBER
LEFT OUTER JOIN OBI_CLICKDATA D
ON A.SESSIONID                    = D.SESSIONID
AND B.LAST_REPORTRUN_CLICK_NUMBER = D.CLICK_NUMBER
LEFT OUTER JOIN
  (SELECT *
  FROM
    (SELECT SESSIONID, REQUEST_GROUP FROM OBI_CLICKDATA
    ) PIVOT (COUNT(*) AS CLICKS FOR (REQUEST_GROUP) IN ( 'Run report' AS RUNREPORT, 'Download/Export' AS DL_EXPORT, 'Find report' AS FINDREPORT, 'Find data' AS FINDDATA, 'Edit report' AS EDITREPORT ))
  ) E
ON A.SESSIONID = E.SESSIONID
GROUP BY A.SAW_USER,
  A.SESSIONID,
  A.USERAGENT,
  A.MOBILE_IND,
  B.FIRST_REPORTRUN_CLICK_NUMBER,
  C.CLICK_TS,
  B.LAST_REPORTRUN_CLICK_NUMBER,
  D.REQUEST_GROUP,
  D.CLICK_TS,
  E.RUNREPORT_CLICKS,
  E.DL_EXPORT_CLICKS,
  E.FINDREPORT_CLICKS,
  E.FINDDATA_CLICKS,
  E.EDITREPORT_CLICKS;

exit
