INSERT INTO OBI_CLICKDATA
WITH CLICKDATA AS (SELECT A.SESSIONID            SESSIONID,
         ROW_NUMBER()
           OVER (
             PARTITION BY SESSIONID
             ORDER BY CLICK_TS) AS CLICK_NUMBER,
         A.CLICK_TS             CLICK_TS,
         A.SAW_USER             SAW_USER,
         A.REQUESTTYPE          REQUESTTYPE,
         B.REQUEST_GROUP,
         A.REQUEST              REQUEST,
         A.FOLDER               FOLDER,
         A.ITEMNAME             ITEMNAME,
         A.EDITORID             EDITORID,
         A.REPORTEDITOR         REPORTEDITOR,
         A.SUBJECTAREA          SUBJECTAREA,
         A.SATABLE              SATABLE,
         A.ACTION               ACTION,
         A.USERAGENT               USERAGENT,
         A.MOBILE_IND               MOBILE_IND,
         A.COOKIE_ORA_BIPS_NQID COOKIE_ORA_BIPS_NQID,
         A.ECID                 ECID
  FROM   OBI_CLICKDATA_STAGE A
         LEFT OUTER JOIN OBI_CLICKDATA_REQUESTGROUP B
                      ON A.REQUEST = B.REQUEST
  WHERE  A.REQUEST IS NOT NULL )
  SELECT * FROM CLICKDATA X WHERE NOT EXISTS (SELECT 1 FROM OBI_CLICKDATA C WHERE X.SESSIONID = C.SESSIONID AND X.CLICK_NUMBER = C.CLICK_NUMBER )
  ORDER  BY CLICK_TS DESC;
COMMIT;
EXIT
